### ISSUE TITLE
Priority in prim1hrpt

### ISSUE THREAD

**Issue by jonseddon** [jonseddon/cmip6-cmor-tables#10]
Several priorities in the prim1hrpt table are floats rather than integers, e.g. rsdsmin has a priority of 2.2.
I'm not sure if this is intentional or an oversight. The other PRIMAVERA specific tables look good.

**Comment by mpmoine** [comment]
Thanks for spotting that point, I was doubtful about the meaning of these non integer priority values as well.

**Comment by jonseddon** [comment]
All priorities changed to 2 in version 1.0.3.
