### ISSUE TITLE
cell_methods 'time:mean' in PRIMAVERA_prim1hrpt.json

### ISSUE THREAD

**Issue by mpmoine** [jonseddon/cmip6-cmor-tables#12]
Hi Jon,

A  minuscule error in PRIMAVERA_prim1hrpt.json but a bit annoying for automatic parsers and to match standards: A white space is missing for 'cell_methods' of 'rsds':
"cell_methods": "**time:mean**" instead of "cell_methods": "**time: mean**"

Thanks,
Marie-Pierre

**Comment by jonseddon** [comment]
Hi Marie-Pierre,

Thanks for spotting that. Are you ok to make that change by hand in your local copy and then we will get it fixed in version 1.0 of the data request?

Thanks,


Jon

**Comment by mpmoine** [comment]
Yes I maid the change by hand in my local copy. 

_"get it fixed in n version 1.0 of the data request"_ means that Primavera Tables will be included in Martin's CMIP6 DR software or you simply  mean that it will be fixed in CMOR3 that gathers Tables for the CMIP6 DR + potential extensions (like Primavera)?

**Comment by jonseddon** [comment]
Sorry, I mean that it will be fixed when we have updated the PRIMAVERA data request to include the changes made to the CMIP6 data request between beta 37 and 1.0, and regenerated the JSON files. David is working on this currently.

**Comment by mpmoine** [comment]
Ok, thanks for the clarification :-)

**Comment by jonseddon** [comment]
Corrected in version 1.0.3.
