### ISSUE TITLE
repeated "mean where sea_ice" in PRIMAVERA_primSIday.json

### ISSUE THREAD

**Issue by mpmoine** [jonseddon/cmip6-cmor-tables#13]
Hi Jon,

there is 'cell_methods' attributes in PRIMAVERA_primSIday.json for which "area: mean where sea_ice" is repeated twice. Its occurs for 8 variables.

Thanks,
Marie-Pierre.

**Comment by jonseddon** [comment]
Changed to `area: time: mean where sea_ice` in the affected cases. Fixed in v1.0.3.
