### ISSUE TITLE
2 different names for 100m depth ('olev100' and 'olev100m')

### ISSUE THREAD

**Issue by mpmoine** [jonseddon/cmip6-cmor-tables#14]
Hi Jon,

Sorry to post so many issues... ;-)

Some oceanic variables are requested at 100m depth, but there is 2 different names used for this level:

PRIMAVERA_primO6hr.json:            "dimensions": "longitude latitude **olev100m** time", 
PRIMAVERA_primO6hr.json:            "dimensions": "longitude latitude **olev100m** time", 
PRIMAVERA_primOday.json:            "dimensions": "longitude latitude **olev100** time", 
PRIMAVERA_primOday.json:            "dimensions": "longitude latitude **olev100** time", 

I gess the correct name is "olev100m". 

Marie-Pierre.

**Comment by jonseddon** [comment]
Brilliant, thanks for identifying that.

It's great to have all of the issues identified here.


Thanks,

Jon

**Comment by mpmoine** [comment]
Hi Jon,

To complete :  neither 'olev100' nor 'olev100m' are defined in PRIMAVERA_coordinate.json.

Regards,
Marie-Pierre.

**Comment by mpmoine** [comment]
Alternative is that neither 'olev100' nor 'olev100m' should exist but should be replaced by **'depth100m'** (that is fully defined in coordinate table). Unless I missed a subtelty in the definition of 'olev100(m)'....

**Comment by jonseddon** [comment]
Both `olev100` and `olev100m` should be the same dimension. `depth100m` is a single depth, but these variables are requested for all levels from the surface to 100 m. Would `olevel` be a more appropriate dimension? I'm not sure how to define a coordinate over multiple levels, which could be different for the three groups that are going to produce these variables (yourselves, AWI and MPI). What would be the best definition to work with your system?

**Comment by mpmoine** [comment]
Thanks for the clear definition (I missed it). You are right,  it is unfeasible to define 'olev100m' as a common. 

As we (CERFACS) rely on XIOS to produce CMOR-compliant Netcdf files, I plan to use the concept of "zoom" over an axis to solve that point. Thus there is no need to change dimension from 'olev100' to 'olev' for the varialbes in question.

Thanks,
Marie-Pierre

**Comment by jonseddon** [comment]
olev100 and olev100m have been changed to olevel in version 1.0.3
