### ISSUE TITLE
sfcWind in prim3hrpt: cell_methods should be "time: point"

### ISSUE THREAD

**Issue by mpmoine** [jonseddon/cmip6-cmor-tables#15]
Hi Jon,

sfcWind in prim3hrpt: cell_methods is `"time: maximum"` but I think should be `"time: point"`.

Thanks,
Marie-Pierre.

**Comment by jonseddon** [comment]
Hi Marie-Pierre,

The maximum is required for some of the processing and so that cell_methods is correct. Instead we believe that the variable should be renamed sfcWindmax and moved to the prim3hr table.

Thanks,

Jon

**Comment by mpmoine** [comment]
Ok,  keeping `'time: maximum'` and renaming as `'sfcWindmax'` sounds good.

Thx,
Marie-Pierre.

**Comment by jonseddon** [comment]
The variable has been moved in version 1.0.3.
