### ISSUE TITLE
prim1hrpt table name

### ISSUE THREAD

**Issue by jonseddon** [jonseddon/cmip6-cmor-tables#16]
Hi @mpmoine

After looking at #15 I checked the other PRIMAVERA time point tables. There are a mixture of cell_methods in the prim1hrpt table (e.g. time mean, point, maximum and minimum). Rather than splitting this table into two tables, we propose that this should be renamed to prim1hr and to keep all of the 1 hour variables in this table.

I am just doing a final check of the v1.0.2 data request and I will send this out by the end of Friday with all of these corrections. I will try to add in the v1.0.3 changes too, although these are minimal.

Thanks,

Jon

**Comment by mpmoine** [comment]
The only constraint is not to have twice the same variable name (with different cell_methods)  in  the same table, but since this criteria is already satisfied in the current 'prim1hrpt',  I have no objection with  renaming to 'prim1hr'.

Marie-Pierre.

**Comment by jonseddon** [comment]
Fixed in v1.0.3.
