### ISSUE TITLE
reverse order for dimensions 'latitude|longitude' in prim1hrpt

### ISSUE THREAD

**Issue by mpmoine** [jonseddon/cmip6-cmor-tables#18]
Hi Jon,

Thanks to you and David for this huge work of rebasing the Primavera Tables on DR 1.0.3.

There is still `latitude|longitude` ordering problem for 2 variables in prim1hrpt (by the way,  should'nt this table be named 'prim1hr**P**t'  to be consistent with others time-point tables ?)

> Warning: spatial shape corresponding to  latitude|longitude for variable wsgsmax in Table PRIMAVERA_prim1hrpt  not found.
> Warning: spatial shape corresponding to  latitude|longitude for variable sfcWindmin in Table PRIMAVERA_prim1hrpt  not found.

Regards,
Marie-Pierre.

**Comment by jonseddon** [comment]
Hi Marie-Pierre,
Sorry, I'm afraid that was an oversight by me. I had forgotten to delete the JSON files for tables that no longer exist. prim1hrpt was renamed to Prim1hr as it contained a mixture of time mean and time point values. I have just checked and the longitude/latitude ordering is correct for all variables in the new table. Commit cbc0ea8 should fix this problem.
Thanks,
Jon

**Comment by mpmoine** [comment]
Great!
Thanks,
Marie-Pierre.
