### ISSUE TITLE
20 variables have no 'modeling_realm' associated in Primday/PrimdayPt

### ISSUE THREAD

**Issue by mpmoine** [jonseddon/cmip6-cmor-tables#20]
Hi Jon,

There are 20 variables having no `modeling_realm` attribute in Primday/PrimdayPt tables. Should be 'atmos'.

> PRIMAVERA_Primday.json-        "zg19": {
> PRIMAVERA_Primday.json:            "modeling_realm": "", 
> PRIMAVERA_Primday.json-        "va23": {
> PRIMAVERA_Primday.json:            "modeling_realm": "", 
> PRIMAVERA_Primday.json-        "zg10": {
> PRIMAVERA_Primday.json:            "modeling_realm": "", 
> PRIMAVERA_Primday.json-        "hus10": {
> PRIMAVERA_Primday.json:            "modeling_realm": "", 
> PRIMAVERA_Primday.json-        "ua10": {
> PRIMAVERA_Primday.json:            "modeling_realm": "", 
> PRIMAVERA_Primday.json-        "hus19": {
> PRIMAVERA_Primday.json:            "modeling_realm": "", 
> PRIMAVERA_Primday.json-        "ua19": {
> PRIMAVERA_Primday.json:            "modeling_realm": "", 
> PRIMAVERA_Primday.json-        "wap23": {
> PRIMAVERA_Primday.json:            "modeling_realm": "", 
> PRIMAVERA_Primday.json-        "hus23": {
> PRIMAVERA_Primday.json:            "modeling_realm": "", 
> PRIMAVERA_Primday.json-        "ta23": {
> PRIMAVERA_Primday.json:            "modeling_realm": "", 
> PRIMAVERA_Primday.json-        "zg23": {
> PRIMAVERA_Primday.json:            "modeling_realm": "", 
> PRIMAVERA_Primday.json-        "va19": {
> PRIMAVERA_Primday.json:            "modeling_realm": "", 
> PRIMAVERA_Primday.json-        "va10": {
> PRIMAVERA_Primday.json:            "modeling_realm": "", 
> PRIMAVERA_Primday.json-        "ta19": {
> PRIMAVERA_Primday.json:            "modeling_realm": "", 
> PRIMAVERA_Primday.json-        "ta10": {
> PRIMAVERA_Primday.json:            "modeling_realm": "", 
> PRIMAVERA_Primday.json-        "ua23": {
> PRIMAVERA_Primday.json:            "modeling_realm": "", 
> PRIMAVERA_Primday.json-        "wap19": {
> PRIMAVERA_Primday.json:            "modeling_realm": "", 
> PRIMAVERA_Primday.json-        "wap10": {
> PRIMAVERA_Primday.json:            "modeling_realm": "", 
> PRIMAVERA_PrimdayPt.json-        "va": {
> PRIMAVERA_PrimdayPt.json:            "modeling_realm": "", 
> PRIMAVERA_PrimdayPt.json-        "ua": {
> PRIMAVERA_PrimdayPt.json:            "modeling_realm": "", 
> 

This also occurs in CMIP6 Tables, but for a smallest number of variables:

> CMIP6_E3hr.json-        "uas": {
> CMIP6_E3hr.json:            "modeling_realm": "", 
> CMIP6_E3hr.json-        "vas": {
> CMIP6_E3hr.json:            "modeling_realm": "", 
> CMIP6_Eday.json-        "hursminCrop": {
> CMIP6_Eday.json:            "modeling_realm": "", 
> CMIP6_Efx.json-        "areacella": {
> CMIP6_Efx.json:            "modeling_realm": "", 
> CMIP6_Emon.json-        "hursminCrop": {
> CMIP6_Emon.json:            "modeling_realm": "", 
> CMIP6_Eyr.json-        "vegFrac": {
> CMIP6_Eyr.json:            "modeling_realm": "", 

Regards,
Marie-Pierre.

**Comment by jonseddon** [comment]
Hi Marie-Pierre,
Yes, the modeling realm for those PRIMAVERA variables should be atmos. Are you ok to add this in your local copy of the tables and I will update the spreadsheet and Github version on Monday?
For the CMIP6 variables, the modeling realm is missing from the CMIP6 data request at http://clipc-services.ceda.ac.uk/dreq/u/7b1a301c-a220-11e6-a33f-ac72891c3257.html. Either, could you create an issue at https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues, or else I can do this on Monday?

Thanks,

Jon

**Comment by mpmoine** [comment]
Hi Jon,
Yes I am ok to modify this in my local copy and to open an issue on the DataRequest github.
Regards,
Marie-Pierre

**Comment by jonseddon** [comment]
Hi Marie-Pierre,

I have just updated the data request and files and modeling realm has been added to the variables in Primday and PrimdayPt. We were not able to decide on a realm for some of the CMIP6 variables (a mixture of atmos and land but we were not certain) and so we have left these until they are updated in the CMIP6 data request.

Thanks,

Jon
