### ISSUE TITLE
5 variables without standard_name

### ISSUE THREAD

**Issue by mpmoine** [jonseddon/cmip6-cmor-tables#22]
Hi Jon,

There is 5 variables having no standard names:

> PRIMAVERA_Prim3hrPt.json-        "vortmean": {
> PRIMAVERA_Prim3hrPt.json-            "modeling_realm": "atmos", 
> PRIMAVERA_Prim3hrPt.json:            "standard_name": "", 
> 
> PRIMAVERA_PrimmonZ.json-        "epfluxdiv": {
> PRIMAVERA_PrimmonZ.json-            "modeling_realm": "atmos", 
> PRIMAVERA_PrimmonZ.json:            "standard_name": "", 
> 
> PRIMAVERA_PrimmonZ.json-        "wstarbar": {
> PRIMAVERA_PrimmonZ.json-            "modeling_realm": "atmos", 
> PRIMAVERA_PrimmonZ.json:            "standard_name": "", 
> 
> PRIMAVERA_PrimmonZ.json-        "xnonoroggwdparam": {
> PRIMAVERA_PrimmonZ.json-            "modeling_realm": "atmos", 
> PRIMAVERA_PrimmonZ.json:            "standard_name": "", 
> 
> PRIMAVERA_PrimmonZ.json-        "ynonoroggwdparam": {
> PRIMAVERA_PrimmonZ.json-            "modeling_realm": "atmos", 
> PRIMAVERA_PrimmonZ.json:            "standard_name": "", 
 
Thanks,
Marie-Pierre.

**Comment by jonseddon** [comment]
Hi Marie-Pierre,

The only variable that I can help with is Prim3hrPt/vortmean, which has a standard name of  atmosphere_relative_vorticity.

There is not a CF standard name defined for the other parameters. While checking I noticed that the standard name in the spreadsheet for PrimmonZ/vstarbar ends with a question mark and so may not be a valid standard name. I will confirm with someone and correct this.

As a standard name does not exist for these variables is it ok to leave the standard name blank? Cmor does not complain if the standard name is blank. The netCDF file produced passes the CF compliance check with no standard name.

I am meeting with David on Wednesday 15th March and we will decide then how to release updated versions of the data request. After the meeting I will make the change to vortmean and vstarbar.

Thanks,

Jon

**Comment by jonseddon** [comment]
Hi Marie-Pierre,

I have just updated the files and vortmean now has a standard name supplied. I still need to find someone who can confirm the standard name for vstarbar.


Thanks,

Jon

**Comment by mpmoine** [comment]
Thanks Jon.

You are right, the CMOR checker does not complain when a standard name is blank both in the file and in the Table (empty string matches empty string ;-))

My concern with blank standard names was because I tried t automatically analyse the DR and Prim Tables using standard name. But I found a different way to do this.

Marie-Pierre.

**Comment by jonseddon** [comment]
Hi Marie-Pierre,

Thanks for that. I've just had vstarbar's standard name confirmed and this has been corrected.

Thanks,

Jon
