### ISSUE TITLE
Generic levels missing in PRIMAVERA tables

### ISSUE THREAD

**Issue by jvegreg** [jonseddon/cmip6-cmor-tables#42]
Some PRIMAVERA specific tables are missing the generic level definitions. In particular:

- olevel: missing in PrimO6hr, PrimOday and PrimOmon
- alevel: missing in Prim6hr and Primmon

**Comment by jonseddon** [comment]
Hi Javier,

I'm not very familiar with the generic_levels value in the header of the tables. Before I change anything I am keen to understand what effect the change will have on other users of the tables.

What problems are you experiencing with the lack of a generic_levels value at the moment?

Thanks,

Jon

**Comment by jvegreg** [comment]
Hi Jon

The generic levels represent the model levels and  are not present in the coordinates tables because they change with every model. I have detected the error because the CMOR checker that is incorporated into ESMValTool uses them to detect the coordinates that it must not look for in the coordinates table

The CMOR library does not use it for cmorization, so users should not notice any change. 

Thanks,
Javi

**Comment by jonseddon** [comment]
Hi Javi,

Thanks for that explanation. I've manually added those changes in now.

Thanks,

Jon
