### ISSUE TITLE
variations across variable out_name and long_name for "wsgmax"

### ISSUE THREAD

**Issue by mpmoine** [jonseddon/cmip6-cmor-tables#6]
In CMIP6 Tables CMIP6_6hrPlev we have :  
- "wsgmax100m" defined as "Maximum Wind Speed of Gust at 100m"

In Primavera Tables CMIP6_prim1hrpt :
- "wsgsmax100" defined as "maximum 100m wind speed gust"
- "wsgsmax"  defined as "Maximum Near-Surface Wind Speed of Gust"
- "wsgsmax50" defined as "maximum 50m wind speed gust"

In Primavera Tables CMIP6_prim6hrpt  :
- "wsgsmax" defined as "Daily Maximum Near-Surface Wind Speed of Gust"

They all share the same standard name "wind_speed_of_gust".

Variations across metadata like:
- output name : "wsg**s**max" , "wsgmax", "wsgmax**100m**", "wsgsmax**100**"
- long name: "**Daily** maximum...", " Maximum... **at 100m**", "**100m** wind gust...", etc.

raise difficulties when automatically parsing the Tables.

**Comment by jonseddon** [comment]
Hi Marie-Pierre,

David's currently updating the data request spreadsheet that these tables are derived from and so I will get these corrected.

Thanks,

Jon

**Comment by jonseddon** [comment]
The two PRIMAVERA tables have now hopefully been made consistent with 6hrPlev. This has been implemented in version 1.0.3. 

Please let me know if these can be further improved!
