### ISSUE TITLE
wrong dimensions ordering for "wsgsmax" and "SfcWindmin"

### ISSUE THREAD

**Issue by mpmoine** [jonseddon/cmip6-cmor-tables#7]
"wsgsmax" and "SfcWindmin" in "CMIP6_prim1hrpt" is the only one to have dimensions expressed with latitude first:
"**latitude** longitude height10m time" instead of "**longitude** latitude height10m time"

**Comment by jonseddon** [comment]
Hi Marie-Pierre,

David's currently updating the data request spreadsheet that these tables are derived from and so I will get these corrected.

Thanks,

Jon

**Comment by jonseddon** [comment]
Corrected in v1.0.3.
