### ISSUE TITLE
Keep track of 'priority' information in PRIMAVERA Json Tables?

### ISSUE THREAD

**Issue by mpmoine** [jonseddon/cmip6-cmor-tables#8]
This is more a question than an issue...

Is there any possibility to include 'priority' information in PRIMAVERA Json Tables as an additional variable attributes?

If this does not disrupt CMOR3, it would be great to keep track of priority information.

Thanks.

**Comment by jonseddon** [comment]
Hi Marie-Pierre,

jonseddon/cmip6-cmor-tables#9 includes priority in only the PRIMAVERA specific tables. I have tested this with our CMOR3.1 solution and it doesn't cause any problems.

Is this what you were after?


Thanks,

Jon

**Comment by mpmoine** [comment]
Hi Jon,
Yes, this is exactly what I needed. Having priority info only in PRIMAVERA specific tables is sufficient.
Thanks a lot !
Marie-Pierre.

**Comment by jonseddon** [comment]
Hi Marie-Pierre,
I've merged that change in now and also updated the mip_era for the PRIMAVERA specific tables. David's still examining the changes to version 1 of the data request and so master branch is still running from beta 45.
Thanks,
Jon
